# Generated by Django 5.1 on 2024-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('flips_quantity', models.IntegerField()),
                ('used_time', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('has_completed', models.BooleanField()),
            ],
        ),
    ]
